#!/usr/bin/bash


gwlaunch_log() {
	echo "$(date +%Y-%m-%d_%H:%M:%S) geneweb-launch: $1"
}

set_db_config() {
	SETTING_NAME=${1,,}
	SETTING_VALUE=$2
	gwlaunch_log "-- Setting $SETTING_NAME to $SETTING_VALUE in database ${GENEWEB_DB}."
	if grep -q "^$SETTING_NAME=.*$" ${GENEWEB_DB_PATH}.gwf; then
		sed -i "s/^$SETTING_NAME=.*$/$SETTING_NAME=$SETTING_VALUE/" ${GENEWEB_DB_PATH}.gwf
	else
		echo "$SETTING_NAME=$SETTING_VALUE" >> ${GENEWEB_DB_PATH}.gwf
	fi
}



# Create default database if it doesn't exist
if [ ! -f ${GENEWEB_DB_PATH}.gwf ] || [ ! -d ${GENEWEB_DB_PATH}.gwb ]; then
	gwlaunch_log "Database ${GENEWEB_DB} not found, creating empty database..."
	cd ${GENEWEB_DB_PATH} || exit 1
	${GENEWEB_HOME}/gw/gwc -f -o ${GENEWEB_DB} > comm.log 2>&1
	cp ${GENEWEB_HOME}//gw/a.gwf ${GENEWEB_DB_PATH}/${GENEWEB_DB}.gwf
	#set_db_config "wizard_passwd_file" "wizard_passwd"
#	echo "${GENEWEB_ADMIN}:${GENEWEB_ADMIN_PASS}" >> ${GENEWEB_HOME}/share/data/wizard_passwd
#	gwlaunch_log "Configured access control."
#	gwlaunch_log "-- ADMIN USERNAME: ${GENEWEB_ADMIN}"
#	gwlaunch_log "-- ADMIN PASSWORD: ${GENEWEB_ADMIN_PASS}"
else
	gwlaunch_log "Database ${GENEWEB_DB} exists."
fi

gwlaunch_log "Adding ${GWSETUP_IP} to allowed range"
echo "${GWSETUP_IP}" > ${GENEWEB_DB_PATH}/only.txt


#gwlaunch_log "Configuring settings for database ${GENEWEB_DB}"...
for setting in $(env | grep GENEWEB_CONFIG_); do
	set_db_config "$(echo "${setting#GENEWEB_CONFIG_}" | cut -f1 -d=)" "$(echo "${setting#GENEWEB_CONFIG_}" | cut -f2 -d=)"
done

#gwlaunch_log "Setting correct ownership of geneweb data."
#sudo chown -R geneweb:geneweb ${GENEWEB_HOME}/share/data
#chown -R geneweb:geneweb ${GENEWEB_HOME}/etc
#chown -R geneweb:geneweb ${GENEWEB_HOME}/log
#gwlaunch_log "-- Set ownership of geneweb data."
